# main text of home
title: Seyyed Mahdi MirRezaei
bio: BSc. in Computer Engineering

# external-image: false 
# picture: assets/images/profile.jpg

dark-theme: auto

# resume: true
# resume-external: true
# resume-url: resume.pdf

url: https://mahdi-mirz.github.io/

disqus:
  shortname: github # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

twitter: SMirrezaei
instagram: mhdi-rrz
github: mahdi-mirz
email: mmirrezaei@yahoo.com

authors:
    seyyedmahdimirrezaei:
    name: Seyyed Mahdi MirRezaei
    bio: BSc. in Computer Enginnering
    external-image: false
    picture: assets/images/profile.jpg
    twitter: SMirrezaei

width: large


url: https://mahdi-mirz.github.io/
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-paginate-v2
  - jekyll-sitemap

